config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'user_orders', to: 'pages#user_orders', as: :user_orders
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/m_international_user_order.rb
class MInternationalUserOrder < ApplicationRecord
  def self.refresh
    Scenic.database.refresh_materialized_view(table_name, concurrently: false, cascade: false)
  end

  # this isn't strictly necessary, but it will prevent
  # rails from calling save, which would fail anyway.
  def readonly?
    true
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :account
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    query = <<-SQL
      SELECT *
      FROM m_international_user_orders
    SQL

    @international_orders = ActiveRecord::Base.connection.execute(query).to_a
  end

  def user_orders
    # to do: display total orders and account_type per user
    query = <<-SQL
      SELECT
        _user_id,
        _user_name,
        _user_phone,
        COUNT(id) as total_orders
      FROM m_international_user_orders
      GROUP BY 1, 2, 3
    SQL

    @international_total_orders = ActiveRecord::Base.connection.execute(query).to_a
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SQL Views</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= link_to "Orders per user >>", user_orders_path, class: "btn btn-info m-3" %>
<h1 class="my-3 text-center">International orders</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <% @international_orders.first.each do |key,value| %>
        <th scope="col"><%= key %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
      <% @international_orders.each_with_index do |order, i| %>
      <tr>
      <th scope="row"><%= i + 1 %></th>
        <% order.each do |_, value| %>
          <td><%= value %></td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/pages/user_orders.html.erb
<%= link_to "<< All orders", root_path, class: "btn btn-info m-3" %>
<h1 class="m-3 text-center">
  International orders per user
</h1>


<% if @international_total_orders %>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <% @international_total_orders.first.each do |key,value| %>
          <th scope="col"><%= key %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
        <% @international_total_orders.each_with_index do |order, i| %>
        <tr>
        <th scope="row"><%= i + 1 %></th>
          <% order.each do |_, value| %>
            <td><%= value %></td>
          <% end %>
        </tr>
        <% end %>
    </tbody>
  </table>
<% else %>
  <p class="m-3 text-center">TODO: Show total amount of orders per user</p>
<% end %>